from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

def generate_pdf(filename, metadata):
    report_name = f"{filename}_metadata_report.pdf"
    report_path = os.path.join(REPORT_DIR, report_name)

    c = canvas.Canvas(report_path, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "Metadata Leakage Scanner")

    c.setFont("Helvetica", 10)
    c.drawString(50, height - 70, "Cybersecurity Metadata Exposure Assessment")

    c.line(50, height - 80, width - 50, height - 80)

    # Scan Info
    c.setFont("Helvetica", 11)
    c.drawString(50, height - 110, f"Scanned File: {filename}")
    c.drawString(50, height - 130, f"Scan Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Metadata Section
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, height - 170, "Extracted Metadata")

    y = height - 200
    c.setFont("Helvetica", 10)

    if metadata:
        for key, value in metadata.items():
            c.drawString(60, y, f"{key}: {value}")
            y -= 15
            if y < 80:
                c.showPage()
                y = height - 80
                c.setFont("Helvetica", 10)
    else:
        c.drawString(60, y, "No metadata found.")

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Generated by Metadata Leakage Scanner")

    c.save()
    return report_name
